### ISSUE TITLE
Multi-GPU training possible?

### ISSUE THREAD

**Issue by KiON-GiON** [HirCoir/Piper-tts#2]
Since this script is made for Kaggle, they have a T4 x2 GPU. This could speed the training and finetuning process of a voice.
I tried to do it, modifying the option `--devices 1` to `--devices 2`, but I got no success. Have you tried it?

Thanks!

**Comment by HirCoir** [comment]
> Since this script is made for Kaggle, they have a T4 x2 GPU. This could speed the training and finetuning process of a voice. I tried to do it, modifying the option `--devices 1` to `--devices 2`, but I got no success. Have you tried it?
> 
> Thanks!

I have tried to do the same but in Kaggle it is not possible to use both GPUs, I have consulted with other developers and they have the same problem

**Comment by KiON-GiON** [comment]
Oh I see. It is really a shame.

**Comment by KiON-GiON** [comment]
Hi there @HirCoir.
I made a personal [branch](https://github.com/KiON-GiON/piper/tree/ddp), modified a bit the Piper trainer to allow Distributed Data Parallel, so the two GPUs work now. In the Kaggle notebook, I did this too:
```
!pip install -q cython>=0.29.0 piper-phonemize==1.1.0 librosa>=0.9.2 numpy==1.24 onnxruntime>=1.11.0 pytorch-lightning~=1.9.0 torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
!pip install --force-reinstall numpy==1.26.4
# fixing recent compativility isswes:+
!pip install -q torchmetrics==0.11.4
```
However, keep in mind you won't suddenly get 32 GB VRAM, it just means it will speed up the training batches. You're still limited to the memory each GPU has.
Also I modified a bit the logger because for some reason Kaggle didn't print information like Colab.
Please test if this works for you.
